// Copyright 2026 Daniel
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define LEADER_TIMEOUT 400
#define LEADER_PER_KEY_TIMING

// From Oryx config
#define ONESHOT_TAP_TOGGLE 2
#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 4000
#define USB_SUSPEND_WAKEUP_DELAY 0
#define LAYER_STATE_8BIT

// Navigator trackball
#define MOUSE_EXTENDED_REPORT
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 2
#define AUTO_MOUSE_TIME 650
#define AUTO_MOUSE_THRESHOLD 10
#define NAVIGATOR_SCROLL_DIVIDER 50
#define NAVIGATOR_SCROLL_INVERT_Y
